volumes:
  pg_data_production:
  static_volume:
  media_volume:
  frontend_build:

services:
  db:
    container_name: foodgram-db
    image: postgres:13.10
    env_file: .env
    restart: always
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    container_name: foodgram-backend
    image: 0legrogovenko/foodgram_backend
    env_file: .env
    restart: always
    depends_on:
      - db
    volumes:
      - static_volume:/app/collected_static
      - media_volume:/media

  frontend:
    container_name: foodgram-frontend
    image: 0legrogovenko/foodgram_frontend
    restart: always
    volumes:
      - frontend_build:/app/build

  gateway:
    container_name: foodgram-gateway
    image: 0legrogovenko/foodgram_gateway
    restart: always
    env_file:
      - .env
    depends_on:
      - backend
      - frontend
    ports:
      - 9090:80
    volumes:
      - frontend_build:/usr/share/nginx/html
      - static_volume:/static
      - media_volume:/media