volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    container_name: foodgram-db
    image: postgres:13.10
    env_file: .env
    restart: always
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    container_name: foodgram-backend
    image: 0legrogovenko/foodgram_backend
    env_file: .env
    restart: always
    depends_on:
      db:
    volumes:
      - static_volume:/app/collected_static
      - media_volume:/media

  frontend:
    container_name: foodgram-frontend
    image: 0legrogovenko/foodgram_frontend
    env_file: .env
    restart: always
    volumes:
      - static_volume:/app/collected_static
      - media_volume:/media
    ports:
      - "9091:80"

  gateway:
    container_name: foodgram-gateway
    image: 0legrogovenko/foodgram_gateway
    env_file: .env
    restart: always
    depends_on:
      backend:
        condition: service_started
    volumes:
      - static_volume:/app/collected_static
      - media_volume:/media
    ports:
      - "9090:80"

networks:
  default:
    name: foodgram-network
