volumes:
  pg_data:
  static_volume:
  media_volume:
  frontend_build:
services:
  db:
    image: postgres:13
    env_file: .env
    volumes: 
      - pg_data:/var/lib/postgresql/data/
  backend:
    container_name: foodgram-backend
    build: ./backend/
    env_file: .env
    volumes:
      - static_volume:/app/collected_static/
      - media_volume:/app/media
      - ./data:/app/data
    depends_on:
      - db
  frontend:
    container_name: foodgram-frontend
    build: ./frontend
    volumes:
      - frontend_build:/frontend_build
    depends_on:
      - backend
  gateway:
    container_name: foodgram-gateway
    image: nginx:1.22.1
    ports:
      - 9090:80
    volumes:
      - frontend_build:/usr/share/nginx/html
      - static_volume:/staticfiles 
      - media_volume:/media 
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
